### PR TITLE
Mandatory app features

### PR DESCRIPTION
**Pull request by warpech**
Proposal of mandatory features that should be included in all of our prefab apps.

Conforming to it enables us to solve problems described in https://github.com/Starcounter/Home/issues/156.

Partially implements: https://github.com/Starcounter/Guidelines/issues/26

@Starcounter/sc-apps any comments?

### CODE REVIEW

**Comment by Mackiovello** [comment]
There are both good and bad parts about this. The good part is that it creates a more uniform experience and makes apps more understandable for users. I think not creating any sample data without the user's consent is especially good. Although, I think it goes back to the topic of production vs. development. In a production environment, there shouldn't even be a question about it - there should never be any sample data. The same applies to the welcome message.

What I'm concerned about are bloat and maintenance. Will the time spent implementing and maintaining these things be worth more than the time saved by these features? We're already struggling with maintaining the existing apps, this will make it even harder to (1) build new apps and (2) maintain and improve existing apps.

- Remove the requirement for a welcome message. With this welcome message, there will have to be a description of the app in at least three places, the GitHub description, the README, the Warehouse, and now the welcome message. If these are not in sync, it will become misinformation and cause confusion. 
- I completely agree with having an entry point URL with a splash screen if there's none. That would require very little maintenance and is useful.
- I'm not confident that having an app icon should be a universal requirement, especially since it relies on Launchpad. I would make it a requirement for all apps that have a meaningful main screen.

Should we have the blendable views in a separate file? What is the motivation for that?
Having the purpose of the apps is a good idea.
I would also like to hear the motivation for why required data shouldn't be added automatically.

**Comment by mmnosek** [comment]
The first question that comes to my mind: Are we going to use it internally, or as an external guideline for all apps in the warehouse? I think it would be nice to make it public. Standardized documentation makes things easier.

I really like the idea and content except things below. All the rest sounds great :)

I dislike:
* The word "mandatory". Suggested or recommended sounds better, especially if it's for external usage. If it's internal mandatory is fine.
* Mentioning GitHub everywhere (if it's external). Some people use something else.
* Splash screen idea. It has no value as I can check if App is running in Starcounter Admin.
* Example with countries in sample data. I would rather prefer to have these countries by default
* A way of creating sample data. It should not be in the interface, rather accessible by some uri (e.g. restricted to localhost)
* Welcome message. If only in "development" mode then it's fine. It's 

I'm missing:
* A note, that it's recommended and might be very good, but in some cases, it doesn't make sense to follow some of those. E.g. if it's background service sending emails, probably icon doesn't make sense. If it's adapter app syncing data over TCP back and forth etc.
* How to handle all of this things if my App is not open source (once again, if external)
* Difference between production and development. Most of the features should not be visible in production, but available in development. Some of them (data generation) should be available in production as well, but just over localhost.
* Settings page as a mandatory feature (if there is anything to set)

Mandatory documentation should be also available in the warehouse and Starcounter Admin (I know it's a separate topic, but we can create issues at least). Dev/Production mode is very important otherwise, it will be a mess.

**Comment by warpech** [comment]
> I think not creating any sample data without the user's consent is especially good.

👍

> In a production environment, there shouldn't even be a question about it - there should never be any sample data. The same applies to the welcome message.

Actually my changes are intended for both development and production. When you install, say Microsoft OneNote, it gives you a welcome message and a sample first note, dosn't it?

> What I'm concerned about are bloat and maintenance. Will the time spent implementing and maintaining these things be worth more than the time saved by these features? We're already struggling with maintaining the existing apps, this will make it even harder to (1) build new apps and (2) maintain and improve existing apps.

Without the mandatory features that I listed, the apps are difficult to setup and use. So I think that these rules will save time in the long term.

Also, we can save time by adding samples right in the Docs, instead of links to the samples. In long term, I hope that a pattern emerges that can be enclosed in some NuGet package "Starcounter C# App Toolkit".

> Remove the requirement for a welcome message. With this welcome message, there will have to be a description of the app in at least three places, the GitHub description, the README, the Warehouse, and now the welcome message. If these are not in sync, it will become misinformation and cause confusion.

Fair point. I will change the welcome message from being mandatory to optional. The purpose is that the main page of an app should not leave you with "I don't know what to do with it" kind of impression.

> I completely agree with having an entry point URL with a splash screen if there's none. That would require very little maintenance and is useful.

👍
    
> I'm not confident that having an app icon should be a universal requirement, especially since it relies on Launchpad. I would make it a requirement for all apps that have a meaningful main screen.

Let's make it optional and have the Launchpad app render a default icon if one is not provided. Still, your app will have to provide the `app-name` page with the metadata for it (app name).

> Should we have the blendable views in a separate file? What is the motivation for that?

That's a must, identified long time ago. Main reason: the app must not tamper with data without user's consent. So even if you only get two files from the app vendor (`app.exe` and `app.map.md`), you can be sure that the app only touches the data listed in `app.map.md`. If that file is not provided, the app will only be able to run standalone without any data integration.

> Having the purpose of the apps is a good idea.

👍

> I would also like to hear the motivation for why required data shouldn't be added automatically.

When you have multiple apps, you might have a conflict that one apps' required data is another apps' unwanted data.

But maybe we can solve this by having another rule. If your app has any **required data** then it must be stored in a unmapped database class. Otherwise that is sample data, not required data.

**Comment by warpech** [comment]
Thank you guys so much for very thoughtful responses!

## General notes

@Mackiovello says:

> What I'm concerned about are bloat and maintenance. Will the time spent implementing and maintaining these things be worth more than the time saved by these features? We're already struggling with maintaining the existing apps, this will make it even harder to (1) build new apps and (2) maintain and improve existing apps.

Without the mandatory features that I listed, the apps are difficult to setup and use. So I think that these rules will save time in the long term.

Short term, these features should be easy to apply by copy and paste. Long term, I hope that a pattern emerges that can be enclosed in some NuGet package "Starcounter C# App Toolkit".

----

@mmnosek says:

> The first question that comes to my mind: Are we going to use it internally, or as an external guideline for all apps in the warehouse? I think it would be nice to make it public. Standardized documentation makes things easier.

In the long term, I want this to be a standarised guideline. Without these features, the app shouldn't pass the Warehouse acceptance test. Should I already move this proposal to the **Cookbook**, or keep it in the **Guidelines** for a while?

----

@mmnosek says:

> I dislike:
> - The word "mandatory". Suggested or recommended sounds better, especially if it's for external usage. If it's internal mandatory is fine.

Let's rename the document to "Warehouse acceptance criteria". And then I think it is fair to have the words "Mandatory" and "Recommended".

----

@mmnosek says:

> - Mentioning GitHub everywhere (if it's external). Some people use something else.

I can replace the GitHub links with inline snippets and a link to the GitHub source. There is a reason why we have the apps open source on GitHub - so that others can use them as reference.

----

@mmnosek says:

> - How to handle all of this things if my App is not open source (once again, if external)

Please explain, which of the proposed features are challenging to not open source apps?

----

@Mackiovello says:

> In a production environment, there shouldn't even be a question about it - there should never be any sample data. The same applies to the welcome message.

@mmnosek says:

> - Difference between production and development. Most of the features should not be visible in production, but available in development. Some of them (data generation) should be available in production as well, but just over localhost.

> - Dev/Production mode is very important otherwise, it will be a mess.

Actually my changes are intended for both dev and prod, because Warehouse has production-ready apps.

When you install, say Microsoft OneNote, it gives you a welcome message and a sample first note, dosn't it?

Can you make a list of things that are expected in dev but not in prod?

We don't even have a pattern for distinguishing between dev and prod, so there is nothing I can propose as mandatory now.

----

@mmnosek says:

> - Settings page as a mandatory feature (if there is anything to set)

Great idea, I will add this. I also want the button to reset the required and sample data to be available on the settings page.

----

@mmnosek says:

> - Mandatory documentation should be also available in the warehouse and Starcounter Admin (I know it's a separate topic, but we can create issues at least).

Can you please extend this? Documentation of what? The code, or the blendable views, or how to use the app?

I second @Mackiovello's comment that it is unrealistic for someone to maintain the same thing in multiple places, so maybe we can have a pattern that can use a single source of truth for all these places.

## Blendable views

@Mackivello says:

> Should we have the blendable views in a separate file? What is the motivation for that?

That's a must, identified long time ago. Main reason: the app must not tamper with data without user's consent. So even if you only get two files from the app vendor (`app.exe` and `app.map.md`), you can be sure that the app only touches the data listed in `app.map.md`. If that file is not provided, the app will only be able to run standalone without any data integration.

## App icon

@Mackivello says:

> I'm not confident that having an app icon should be a universal requirement, especially since it relies on Launchpad. I would make it a requirement for all apps that have a meaningful main screen.

@mmnosek says:

>  -  A note, that it's recommended and might be very good, but in some cases, it doesn't make sense to follow some of those. E.g. if it's background service sending emails, probably icon doesn't make sense. If it's adapter app syncing data over TCP back and forth etc.

I agree, I will relax this requirement.

The app must provide metadata that responds to the `app-name` token.

If the app has an entry URI (main screen or splash screen), navigation apps like Launchpad will display a link to that URI.

The metadata can include a `Html` property that includes an icon, otherwise navigation apps like Launchpad will display a default icon.


## Splash screen

@mmnosek says:

>  - Splash screen idea. It has no value as I can check if App is running in Starcounter Admin.

So do you also dislike having mandatory entry point URIs? Because for be these three go together like bread and butter and (*put your favorite sandwich stuff here*):

- app icon
- entry point URI
- splash screen or the main page

Maybe this rule can be relaxed to: If your app has a web UI, it is mandatory to have all 3 of the above.

But in my world, there is no harm in having all 3 even if your app doesn't have a web UI. If the user does not want to see the icon, they can disable it by blending.

## Welcome message

@Mackivello says:

> Remove the requirement for a welcome message. With this welcome message, there will have to be a description of the app in at least three places, the GitHub description, the README, the Warehouse, and now the welcome message. If these are not in sync, it will become misinformation and cause confusion.

@mmnosek says:

> Welcome message. If only in "development" mode then it's fine.

Fair point. I will change the welcome message from being mandatory to optional.
 The purpose is that the main page of an app should not leave you with "I don't know what to do with it" kind of impression.

## Required data

@Mackivello says:

> I would also like to hear the motivation for why required data shouldn't be added automatically.

When you have multiple apps, you might have a conflict that one apps' required data is another apps' unwanted data.

But maybe we can solve this by having another rule. If your app has any **required data** then it must be stored in a unmapped database class. Otherwise that is sample data, not required data.

## Sample data

@mmnosek says:

> Example with countries in sample data. I would rather prefer to have these countries by default

See my response above for required data.

If "countries" are a shared (mapped) table, it must be regarded sample data and not filled in automatically, because what if one app only wants countries that are in the EU and other app only wants countries that have McDonald's in them?

If "countries" is in a unshared (unmapped) table, then we can be fill in automatically as required data.

----

@mmnosek says:

> - A way of creating sample data. It should not be in the interface, rather accessible by some uri (e.g. restricted to localhost)

We have this in SignIn, that you have to visit `/signin/generateadminuser`. Everybody is confused about that, because nobody wants to read READMEs. See: https://github.com/Starcounter/Home/issues/156

It is a nice idea to restrict the UI to `localhost`, but I don't know if it can be done in a hack-proof way (have to check with @joozek). We should not give a sense of fake security. Anyway, I would like to consider it as a next step, not immediately.

**Comment by warpech** [comment]
I have a new idea. I will create a bunch of Cookbook pages about "Settings page", "App icon", etc.

Then the page in topic becomes just a checklist of mandatory features with links to the respective Cookbook pages.

I think that all except the stuff about `README.md` should go to the Cookbook, not Guidelines.

**Comment by warpech** [comment]
All your comments are now implemented as part of the new PR in the Docs: https://github.com/Starcounter/Docs/pull/121

From the current PR I have removed everything except `README.md` improvements and removal of a 404 link in the menu. 

I think that it can be merged without further review.

**Pull request merged**
